> /home/zhongqi/Documents/workspace/G1_sim/koopman_g1.py(145)Klinear_loss()
    144         ipdb.set_trace()
--> 145         if not all_loss:
    146             loss += beta * mse_loss(X_current[:, :Nstate], data[i+1, :, u_dim:])
Traceback (most recent call last):
  File "/home/zhongqi/Documents/workspace/G1_sim/koopman_g1.py", line 355, in <module>
  File "/home/zhongqi/Documents/workspace/G1_sim/koopman_g1.py", line 335, in main
    train_steps=100000,
  File "/home/zhongqi/Documents/workspace/G1_sim/koopman_g1.py", line 264, in train
    x_state = X[0, :, data_collect.udim:]
  File "/home/zhongqi/Documents/workspace/G1_sim/koopman_g1.py", line 145, in Klinear_loss
    loss += beta * mse_loss(X_current[:, :Nstate], data[i+1, :, u_dim:])
  File "/home/zhongqi/Documents/workspace/G1_sim/koopman_g1.py", line 145, in Klinear_loss
    loss += beta * mse_loss(X_current[:, :Nstate], data[i+1, :, u_dim:])
  File "/usr/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
If you suspect this is an IPython 7.34.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True